# Generated by Django 3.2.4 on 2022-11-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='about',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='link',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
