# Generated by Django 3.2.4 on 2022-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0003_auto_20221125_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
